##ERICK GUTIERREZ
#TAMBIEN NO DEJO EJERCCIO Y CREO QUE EN SU PRESENTACION 
# NO ESTA LA PREGUNTA DE EXAMEN
a = 5
b = 10

if a < b:
    print("a es menor que b")





###IGUAL MENTE FUE EL EJERCICIO QUE DEJO EL PROFESOR
CALIFICACION_UNO = 11
CALIFICACION_DOS = 6.7
CALIFICACION_TRESS = 8.7

Promedio = CALIFICACION_UNO+ CALIFICACION_DOS +CALIFICACION_TRESS
Promedio /= 3

if Promedio >= 8.5:
    print("EXENTASTEEE")
else:
    print("Haces examen final ")
